language: python

addons:
  apt:
    sources:
    packages:
    - libopenblas-dev

python:
- '3.6'
install:
- pip install .
script:
- python -m unittest discover -s ./test
deploy:
  provider: pypi
  user: frkhit
  password:
    secure: P4f4jZT09ulT5HGYG+NTrXLXzez/sQU0rYJlbgXdx6ZqDli3KFkK8b7pepUcyUKRx0ORD94v90DDZI9C29eZKhSj9LZf/fh1bbJfBawCFQfo3NcB0Ha9mQGBIN4+jvdqzfAqaVtyW32L/wkwpY4CslwyxvnwpFjK/Lko3rzUwjnbrC7yOrabtkB6mnyiSrovfzHsNO71bebcQQFs00gIxxK5H2+xEOUbzoVWn8VlxLn9zGuBhQtzCp4g+AIe2MrqCCP6fCOSf5eW2OSbCNAObnCITJz+ATa9OlYSRMt2/R2UL59261ZHbKfNVwZVL8TWf0XB+sIBwLFW9Nq7e8rkviD7CYU8eO86B2ePILhc+z3dlTfCDidjLQ85nDYPgwS10zw2fCdD5DpSMMNr5D2EqhoMTD/jwUgp9hYQOrXyA+rzMvZuV9jl6ouTeLIRSw0+V66BKABz4Gewji5YWt9UvsMQOf6/ixzoww7SIeHvhEYUq+UCz4YKXhQbxWFEsA4di7snuubKQEYwMEasIdAC0egW4P6wwc1MV31wUPkiMS4IiI7kmHWs9kF26089VGx5PGk8ckl8nZy5/Elo6gq5/IZIQ+v9O+vvQcq6TvpzTtJYuIuTCYy5u1DAdMTMNchmYkaJLtTkouJiarsbfHIg137jkv0c5UuzuaWPNfAMpv8=
  on:
    python: 3.6
    branch: master
